spring.application.name=jwtFinal

spring.datasource.url=jdbc:mysql://localhost:3306/practice
spring.datasource.username=root
spring.datasource.password=root
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

app.EXPIRATION_TIME = 1000*60*60
app.secret = "my-app-contains-secret-key-mukesh-narayana-1234567890!@#$%^&*()"