spring.application.name=spinghibernateproject

# MySQL DB connections
spring.datasource.url=jdbc:mysql://localhost:3306/coditas
spring.datasource.username=root
spring.datasource.password=root
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.jpa.properties.hibernate.current_session_context_class = org.springframework.orm.jpa.hibernate.SpringSessionContext


# security configurations
spring.security.user.name=mukesh
spring.security.user.password=12345 