spring.application.name=oAuthImplementation

spring.security.oauth2.client.registration.google.client-id=581302668392-usc7j8qi64g1jbap8jpori8mjjgu5d03.apps.googleusercontent.com
spring.security.oauth2.client.registration.google.client-secret=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


spring.datasource.url=jdbc:mysql://localhost:3306/practice
spring.datasource.username=root
spring.datasource.password=root
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true